### ISSUE TITLE
请问loss一直在震荡是什么原因

### ISSUE THREAD

**Issue by WangSong960913** [potterhsu/easy-fpn.pytorch#3]

**Comment by WangSong960913** [comment]
`
![Uploading Screenshot from 2019-12-14 16-47-19.png…]()
`

**Comment by ueoo** [comment]
I think the reason is that there is no mini-batch training.
Could anyone try to implement Mini-Batch as the author's [easy-faster-rcnn](https://github.com/potterhsu/easy-faster-rcnn.pytorch)?
